[package]
name = "decayrate"
version = "0.1.0"
edition = "2021"

[dependencies]
archt = { path = "../archt" }

[dev-dependencies]
rayon = "1.10.0"
clap = { version = "4.5.23", features = ["derive"] }
